--- Create RAW Table

CREATE OR REPLACE TABLE RAW.ATHLETES   (Name STRING, NOC STRING, Discipline STRING);


CREATE OR REPLACE TABLE RAW.COACHES    (Name STRING, NOC STRING, Discipline STRING,Event STRING);


CREATE OR REPLACE TABLE RAW.ENTRIES_GENDER (Discipline STRING, Male NUMBER, Female NUMBER, Total NUMBER);

CREATE OR REPLACE TABLE RAW.MEDALS     (Rank Number, "Team/NOC" STRING, Gold Number,Silver Number,Bronze Number,Total Number, "Rank by Total" Number )

CREATE OR REPLACE TABLE RAW.TEAMS  (Name STRING,Discipline STRING, NOC STRING,Event STRING);

SELECT * FROM RAW.ATHLETES
SELECT * FROM RAW.COACHES  
SELECT * FROM RAW.ENTRIES_GENDER 
SELECT * FROM RAW.MEDALS
SELECT * FROM RAW.TEAMS

