--- Create RAW Table

CREATE OR REPLACE TABLE RAW.ATHLETES   (Name STRING, NOC STRING, Discipline STRING);


CREATE OR REPLACE TABLE RAW.COACHES    (Name STRING, NOC STRING, Discipline STRING,Event STRING);


CREATE OR REPLACE TABLE RAW.ENTRIES_GENDER (Discipline STRING, Male NUMBER, Female NUMBER, Total NUMBER);

CREATE OR REPLACE TABLE RAW.MEDALS     (Rank Number, "Team/NOC" STRING, Gold Number,Silver Number,Bronze Number,Total Number, "Rank by Total" Number )

CREATE OR REPLACE TABLE RAW.TEAMS  (Name STRING,Discipline STRING, NOC STRING,Event STRING);

SELECT * FROM RAW.ATHLETES
SELECT * FROM RAW.COACHES  
SELECT * FROM RAW.ENTRIES_GENDER 
SELECT * FROM RAW.MEDALS
SELECT * FROM RAW.TEAMS

---- Load All CSVs file into snowflake RAW table.

COPY INTO RAW.ATHLETES
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Athletes.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT * FROM RAW.ATHLETES
  
COPY INTO RAW.COACHES
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Coaches.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT COUNT(*) FROM RAW.COACHES
  SELECT * FROM RAW.COACHES LIMIT 5;

  
COPY INTO RAW.ENTRIES_GENDER
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*EntriesGender.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT COUNT(*) FROM RAW.ENTRIES_GENDER
  SELECT * FROM RAW.ENTRIES_GENDER LIMIT 5;


COPY INTO RAW.MEDALS
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Medals.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

SELECT COUNT(*) FROM RAW.MEDALS

COPY INTO RAW.Teams
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Teams.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';
  
SELECT COUNT(*) FROM RAW.TEAMS
SELECT * FROM RAW.TEAMS LIMIT 5;



