----CREATE A CLEAN , AGGREGATED TABLE FOR POWER BI
---ATHLETES
CREATE OR REPLACE TABLE ANALYTICS.ATHLETES_CLEAN AS
SELECT DISTINCT
 
  INITCAP(NULLIF(TRIM(NAME),''))      AS ATHLETE_NAME,
  INITCAP(NULLIF(TRIM(NOC),''))     AS NOC,
  INITCAP(NULLIF(TRIM(DISCIPLINE),''))  AS DISCIPLINE
  FROM RAW.ATHLETES
  WHERE NAME IS NOT NULL;

  select * From ANALYTICS.ATHLETES_CLEAN 

---COACHES
CREATE OR REPLACE TABLE ANALYTICS.COACHES_CLEAN AS
SELECT
    INITCAP(NULLIF(TRIM(Name), ''))       AS COACH_NAME,
    UPPER(NULLIF(TRIM(NOC), ''))          AS NOC,
    INITCAP(NULLIF(TRIM(Discipline), '')) AS DISCIPLINE,
    COALESCE(
        INITCAP(NULLIF(TRIM(Event), '')),
        'No event listed'
    )                                     AS EVENT
FROM RAW.COACHES
WHERE EVENT IS NULL

select count(*) From ANALYTICS.COACHES_CLEAN

----Count rows that have any NULL in any column
SELECT COUNT(*) AS rows_with_any_null
FROM RAW.COACHES
WHERE Name IS NULL
   OR NOC IS NULL
   OR DISCIPLINE IS NULL
   OR EVENT IS NULL;
   


----ENTRIES GENDER
CREATE OR REPLACE TABLE ANALYTICS.ENTRIES_GENDER_CLEAN AS
SELECT
  Discipline ,
  COALESCE(TRY_TO_NUMBER(MALE),0)     AS MALE,
  COALESCE(TRY_TO_NUMBER(FEMALE),0)   AS FEMALE,
  COALESCE(TRY_TO_NUMBER(TOTAL),0)    AS TOTAL
FROM RAW.ENTRIES_GENDER;

select count(*) from ANALYTICS.ENTRIES_GENDER_CLEAN

---MEDALS

CREATE OR REPLACE TABLE ANALYTICS.MEDALS_CLEAN AS
SELECT
  gold AS GOLD,
  silver AS SILVER,
  bronze AS BRONZE,
  RANK AS RANK_NUMBER,
  TOTAL AS TOTAL,
  "Rank by Total" AS RANK_BY_TOTAL,
  "Team/NOC"                    AS TEAM_NOC
FROM RAW.MEDALS
WHERE RANK IS NOT NULL;


select * from ANALYTICS.MEDALS_CLEAN 


-- Create normalized “clean” tables with good column names
---TEAMS
CREATE OR REPLACE TABLE ANALYTICS.TEAMS_CLEAN AS
SELECT
  TRIM(Name)      AS Name,
  UPPER(TRIM(NOC))   AS NOC,
  TRIM(DISCIPLINE)   AS DISCIPLINE,
  TRIM(Event) AS Event
  
FROM RAW.TEAMS
where Event is NOT Null

select count(*)
From ANALYTICS.TEAMS_CLEAN







