-- STEP 1: Create a virtual warehouse for compute

CREATE OR REPLACE WAREHOUSE WH_CLOUDLOAD
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for CloudLoad Data Warehouse Integration project';

-- STEP 2: Create a database

CREATE OR REPLACE DATABASE CLOUDLOAD_DB
  COMMENT = 'Database for CloudLoad Data Warehouse Integration project';
  

-- STEP 3: Create two schemas - RAW and ANALYTICS

CREATE OR REPLACE SCHEMA CLOUDLOAD_DB.RAW
  COMMENT = 'Schema to store raw ingested data';

CREATE OR REPLACE SCHEMA CLOUDLOAD_DB.ANALYTICS
  COMMENT = 'Schema for transformed and aggregated data';

-- STEP 4: Use them as your active context
USE WAREHOUSE WH_CLOUDLOAD;
USE DATABASE CLOUDLOAD_DB;
USE SCHEMA CLOUDLOAD_DB.RAW;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE CLOUDLOAD_DB;

--- Create a CSV File format

CREATE OR REPLACE FILE FORMAT csv_std
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null');

--- Create Internal Stage

CREATE OR REPLACE STAGE cloud_stage
  FILE_FORMAT = csv_std
  COMMENT = 'Internal stage for CloudLoad';

  

USE DATABASE CLOUDLOAD_DB;
USE SCHEMA RAW;
LIST @CLOUDLOAD_DB.RAW.cloud_stage;

SHOW STAGES;
--- Create Table

CREATE OR REPLACE TABLE RAW.ATHLETES   (Name STRING, NOC STRING, Discipline STRING);


CREATE OR REPLACE TABLE RAW.COACHES    (Name STRING, NOC STRING, Discipline STRING,Event STRING);


CREATE OR REPLACE TABLE RAW.ENTRIES_GENDER (Discipline STRING, Male NUMBER, Female NUMBER, Total NUMBER);

CREATE OR REPLACE TABLE RAW.MEDALS     (Rank Number, "Team/NOC" STRING, Gold Number,Silver Number,Bronze Number,Total Number, "Rank by Total" Number )

CREATE OR REPLACE TABLE RAW.TEAMS  (Name STRING,Discipline STRING, NOC STRING,Event STRING);

SELECT * FROM RAW.ATHLETES
SELECT * FROM RAW.COACHES  
SELECT * FROM RAW.ENTRIES_GENDER 
SELECT * FROM RAW.MEDALS
SELECT * FROM RAW.TEAMS


---- Load All CSVs file into snowflake RAW table.

COPY INTO RAW.ATHLETES
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Athletes.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT COUNT(*) FROM RAW.ATHLETES
  
COPY INTO RAW.COACHES
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Coaches.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT COUNT(*) FROM RAW.COACHES
  SELECT * FROM RAW.COACHES LIMIT 5;

  
COPY INTO RAW.ENTRIES_GENDER
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*EntriesGender.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

  SELECT COUNT(*) FROM RAW.ENTRIES_GENDER
  SELECT * FROM RAW.ENTRIES_GENDER LIMIT 5;


COPY INTO RAW.MEDALS
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Medals.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';

SELECT COUNT(*) FROM RAW.MEDALS

COPY INTO RAW.Teams
  FROM @cloud_stage
  FILE_FORMAT=(FORMAT_NAME=csv_std)
  PATTERN='.*Teams.*\\.csv'
  ON_ERROR='ABORT_STATEMENT';
  
SELECT COUNT(*) FROM RAW.TEAMS
SELECT * FROM RAW.TEAMS LIMIT 5;


----CREATE A CLEAN , AGGREGATED TABLE FOR POWER BI
---ATHLETES
CREATE OR REPLACE TABLE ANALYTICS.ATHLETES_CLEAN AS
SELECT DISTINCT
 
  INITCAP(NULLIF(TRIM(NAME),''))      AS ATHLETE_NAME,
  INITCAP(NULLIF(TRIM(NOC),''))     AS NOC,
  INITCAP(NULLIF(TRIM(DISCIPLINE),''))  AS DISCIPLINE
  FROM RAW.ATHLETES
  WHERE NAME IS NOT NULL;

  select count(*) From ANALYTICS.ATHLETES_CLEAN 

---COACHES
CREATE OR REPLACE TABLE ANALYTICS.COACHES_CLEAN AS
SELECT
    INITCAP(NULLIF(TRIM(Name), ''))       AS COACH_NAME,
    UPPER(NULLIF(TRIM(NOC), ''))          AS NOC,
    INITCAP(NULLIF(TRIM(Discipline), '')) AS DISCIPLINE,
    COALESCE(
        INITCAP(NULLIF(TRIM(Event), '')),
        'No event listed'
    )                                     AS EVENT
FROM RAW.COACHES
WHERE EVENT IS NULL

select count(*) From ANALYTICS.COACHES_CLEAN

----Count rows that have any NULL in any column
SELECT COUNT(*) AS rows_with_any_null
FROM RAW.COACHES
WHERE Name IS NULL
   OR NOC IS NULL
   OR DISCIPLINE IS NULL
   OR EVENT IS NULL;
   


----ENTRIES GENDER
CREATE OR REPLACE TABLE ANALYTICS.ENTRIES_GENDER_CLEAN AS
SELECT
  Discipline ,
  COALESCE(TRY_TO_NUMBER(MALE),0)     AS MALE,
  COALESCE(TRY_TO_NUMBER(FEMALE),0)   AS FEMALE,
  COALESCE(TRY_TO_NUMBER(TOTAL),0)    AS TOTAL
FROM RAW.ENTRIES_GENDER;

select count(*) from ANALYTICS.ENTRIES_GENDER_CLEAN

---MEDALS

CREATE OR REPLACE TABLE ANALYTICS.MEDALS_CLEAN AS
SELECT
  gold AS GOLD,
  silver AS SILVER,
  bronze AS BRONZE,
  RANK AS RANK_NUMBER,
  TOTAL AS TOTAL,
  "Rank by Total" AS RANK_BY_TOTAL,
  "Team/NOC"                    AS TEAM_NOC
FROM RAW.MEDALS
WHERE RANK IS NOT NULL;


select * from ANALYTICS.MEDALS_CLEAN 


-- Create normalized “clean” tables with good column names
---TEAMS
CREATE OR REPLACE TABLE ANALYTICS.TEAMS_CLEAN AS
SELECT
  TRIM(Name)      AS Name,
  UPPER(TRIM(NOC))   AS NOC,
  TRIM(DISCIPLINE)   AS DISCIPLINE,
  TRIM(Event) AS Event
  
FROM RAW.TEAMS
where Event is NOT Null

select count(*)
From ANALYTICS.TEAMS_CLEAN


----Count rows that have any NULL in any column
SELECT COUNT(*) AS rows_with_any_null
FROM RAW.TEAMS
WHERE Name IS NULL
   OR NOC IS NULL
   OR DISCIPLINE IS NULL;
   
----Normalize NULLs and blanks.
SELECT
  NULLIF(TRIM(NOC), '') AS NOC,
  NULLIF(TRIM(Event), '') AS Event,
   
FROM RAW.TEAMS;


USE ROLE SYSADMIN;                         
USE WAREHOUSE WH_CLOUDLOAD;
USE DATABASE CLOUDLOAD_DB;


-----Create the clean tables in ANALYTICS

-- TEAMS_CLEAN
CREATE OR REPLACE TABLE ANALYTICS.TEAMS_CLEAN AS
SELECT
  TRIM(Name)                         AS Name,
  UPPER(TRIM(NOC))                      AS NOC,
  INITCAP(TRIM(DISCIPLINE))             AS DISCIPLINE,
  EVENT
  
FROM RAW.TEAMS;
SELECT * FROM ANALYTICS.TEAMS_CLEAN

-- MEDALS_CLEAN
CREATE OR REPLACE TABLE ANALYTICS.MEDALS_Summary AS
SELECT
 TRIM("Team/NOC")                    AS TEAM_NOC,        -- keep as a single text field
  TRY_TO_NUMBER(Gold)                AS GOLD,
  TRY_TO_NUMBER(Silver)              AS SILVER,
  TRY_TO_NUMBER(Bronze)              AS BRONZE,
  TRY_TO_NUMBER(Total)               AS TOTAL,
  RANK                               AS RANK_NUMBER,
  "Rank by Total"                    AS Rank_by_Total
   
FROM RAW.MEDALS
limit 10;
SELECT * FROM ANALYTICS.MEDALS_Summary


---- Medal Count per Team × Sport

USE DATABASE CLOUDLOAD_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.MEDAL_TEAM_CLEAN AS
SELECT
    t.NOC                                  AS NOC,
    COALESCE(m.GOLD,   0)                  AS GOLD,
    COALESCE(m.SILVER, 0)                  AS SILVER,
    COALESCE(m.BRONZE, 0)                  AS BRONZE,
    COALESCE(m.TOTAL,  0)                  AS TOTAL_MEDALS,
    INITCAP(t.Event)                       AS EVENT
FROM ANALYTICS.MEDALS_CLEAN m
JOIN RAW.TEAMS t
      ON UPPER(m.Team_NOC) = UPPER(t.NOC);



SELECT count(event) 
FROM ANALYTICS.MEDAL_TEAM_CLEAN
WHERE EVENT IS NULL;

---- MEDAL PER TEAM

CREATE OR REPLACE TABLE ANALYTICS.MEDAL_TEAM AS
SELECT
  m.TEAM_NOC                   AS TEAM,            
  t.NOC,
  m.GOLD,
  m.SILVER,
  m.BRONZE,
  m.TOTAL        AS TOTAL_MEDALS,
  m.RANK_NUMBER,
  m.RANK_BY_TOTAL
FROM ANALYTICS.MEDALS_CLEAN m
LEFT JOIN ANALYTICS.TEAMS_CLEAN t
    ON UPPER(t.NOC)    = UPPER(m.TEAM_NOC);
 



--- Simple BI View

---Leaderboard (team level):

CREATE OR REPLACE VIEW ANALYTICS.TEAM_LEADERBOARD AS
SELECT DISTINCT TEAM, COALESCE(NOC,'') AS NOC,
       GOLD, SILVER, BRONZE, TOTAL_MEDALS,
       RANK_NUMBER, RANK_BY_TOTAL
FROM ANALYTICS.MEDAL_TEAM
ORDER BY GOLD DESC, SILVER DESC, BRONZE DESC;

SELECT * 
FROM ANALYTICS.TEAM_LEADERBOARD


---- Show athletes whose team/NOC has at least one Gold medal, plus their coach, NOC, and discipline.

USE DATABASE CLOUDLOAD_DB;
USE SCHEMA ANALYTICS;

WITH athlete_coach AS (
    SELECT
        a.Name AS ATHLETE_NAME,
        COALESCE(c.Name, 'No coach listed') AS COACH_NAME,
        a.NOC,
        a.Discipline AS DISCIPLINE,
        m.GOLD,
        ROW_NUMBER() OVER (
            PARTITION BY a.Name, a.NOC, a.Discipline
            ORDER BY c.Name
        ) AS rn
    FROM RAW.ATHLETES a
    JOIN RAW.TEAMS t
        ON UPPER(a.NOC) = UPPER(t.NOC)
    LEFT JOIN RAW.COACHES c
        ON UPPER(c.NOC) = UPPER(a.NOC)
       AND UPPER(c.Discipline) = UPPER(a.Discipline)
    JOIN ANALYTICS.MEDALS_CLEAN m
        ON UPPER(m.TEAM_NOC) = UPPER(t.NOC)
    WHERE m.GOLD > 0
)
SELECT
    ATHLETE_NAME,
    COACH_NAME,
    NOC,
    DISCIPLINE,
    GOLD
FROM athlete_coach
WHERE rn = 1;      -- keep only one coach per athlete


-----Query: Athlete name, NOC, discipline, gender, NOC medal total

CREATE OR REPLACE TABLE ANALYTICS.NOC_DISCIPLINE_GENDER_MEDALS AS
SELECT DISTINCT
    a.NOC,
    a.Discipline,
    e.Female AS TOTAL_FEMALE_IN_SPORT,
    e.Male   AS TOTAL_MALE_IN_SPORT,
    m.GOLD,
    m.SILVER,
    m.BRONZE
FROM RAW.ATHLETES a
LEFT JOIN RAW.ENTRIES_GENDER e
      ON UPPER(a.Discipline) = UPPER(e.Discipline)
JOIN ANALYTICS.MEDALS_CLEAN m
      ON UPPER(m.TEAM_NOC) = UPPER(a.NOC)
WHERE m.GOLD > 0 OR m.SILVER > 0 OR m.BRONZE > 0;



---Athletes with GOLD NOC

CREATE OR REPLACE TABLE ANALYTICS.ATHLETES_GOLD_NOC AS
SELECT DISTINCT
    a.Name AS ATHLETE_NAME,
    COALESCE(c.Name, 'No coach listed') AS COACH_NAME,
    t.NOC  AS NOC,
    a.Discipline  AS DISCIPLINE,
    m.GOLD
FROM RAW.ATHLETES a
JOIN RAW.TEAMS t
      ON a.NOC = t.NOC
LEFT JOIN RAW.COACHES c
      ON c.Discipline = a.Discipline
JOIN ANALYTICS.MEDALS_CLEAN m
      ON UPPER(m.TEAM_NOC) = UPPER(t.NOC)
WHERE m.GOLD > 0;



----Grant Power BI user access.

CREATE ROLE BI_ROLE;
GRANT ROLE BI_ROLE TO USER dev123;


GRANT USAGE ON DATABASE CLOUDLOAD_DB TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE BI_ROLE;

